### ISSUE TITLE
FlexLexer ?

### ISSUE THREAD

**Issue by flosn25** [bertlr/vplotter#1]
i'm trying to compile it, as descripted in the manual and facing:

lex.xx.cc:323:23: fatal error: FlexLexer.h: No such file or directory
#indluce <FlexLexer.h>

**Comment by bertlr** [comment]
please install flex:

sudo apt-get install flex

**Comment by flosn25** [comment]
thx :)

**Comment by bertlr** [comment]
I add flex as required package in the Readme.md
