### ISSUE TITLE
Use of stepper motor Kysan 11240907951

### ISSUE THREAD

**Issue by bastifix** [bertlr/vplotter#3]
Hi!
I already have 2 Kysan 11240907951 stepper motors here, like this one:
https://ultimachine.com/products/kysan-1124090-nema-17-stepper-motor

I tried to attach them as your wiring graphic shows, but none of them is working (not even a bit).
This model has 4 wires with 4 colours, but I found a tutorial that blue and yellow build one coil and green and red. So I thought it should just work when use the 4-plug as it is.
The script and the rest seems to work well, because the servo motor is doing its job. Also the easydrivers are running with the red indicator light.

Is there a way to get these motors running? 

Big thanks and greetings, Basti

**Comment by bertlr** [comment]
The motors seems ok, maybe the easydriver is too small for the current.
Did you run vplotter as root?
Is the connection between easydriver and stepper ok?

**Comment by bastifix** [comment]
Thanks!
I checked everything twice and then found out, that the motors needed more power. So with a larger battery it runs now ;-)
